/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./components/ui/AppBadge.vue')['default']
    AppField: typeof import('./components/ui/AppField.vue')['default']
    AppInput: typeof import('./components/ui/AppInput.vue')['default']
    AppTable: typeof import('./components/ui/AppTable.vue')['default']
    AppTabs: typeof import('./components/ui/AppTabs.vue')['default']
    AppToast: typeof import('./components/ui/AppToast.vue')['default']
    BaseModal: typeof import('./components/ui/BaseModal.vue')['default']
    BuildingIcon: typeof import('@/components/icons')['BuildingIcon']
    CursorArrowIcon: typeof import('@/components/icons')['CursorArrowIcon']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    FilterIcon: typeof import('@/components/icons')['FilterIcon']
    ListIcon: typeof import('@/components/icons')['ListIcon']
    PlusIcon: typeof import('@/components/icons')['PlusIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowActions: typeof import('./components/ui/RowActions.vue')['default']
    SelectableCard: typeof import('./components/ui/SelectableCard.vue')['default']
    SkeletonList: typeof import('./components/ui/SkeletonList.vue')['default']
    XIcon: typeof import('@/components/icons')['XIcon']
  }
}
